(defproject kitjensink "1.0.0-SNAPSHOT"
	:description "FIXME: write description"
  :dependencies [
		[org.clojure/clojure "1.3.0"]
  	[org.clojure/tools.namespace "0.1.2"]
  	[org.clojure/tools.logging "0.2.3"]
  	[org.clojure/tools.cli "0.2.1"]
  	[org.clojure/data.csv "0.1.0"]
  	[org.clojure/data.codec "0.1.0"]
  	[org.clojure/core.unify "0.5.2"]
  	[org.clojure/core.memoize "0.5.1"]
  	[org.clojure/core.match "0.2.0-alpha9"]
  	[org.clojure/core.logic "0.6.8"]
  	[org.clojure/tools.nrepl "0.2.0-beta2"]
  	;[org.clojure/algo.monads "0.1.3-SNAPSHOT"]
  	;[org.clojure/algo.generic "0.1.1-SNAPSHOT"]
  	;[enlive "1.2.0-alpha1"]
  	[fs "1.1.2-FS"]
  	[hiccup "0.3.8"]
  	[com.cemerick/pomegranate "0.0.4"]
  	[marginalia "0.7.0-SNAPSHOT"]
  	[noir "1.3.0-alpha10"]
  	[pinot "0.1.1-SNAPSHOT"]
  	[ns-tracker "0.1.1"]
  	[codox "0.3.4"]
  	[org.clojure/tools.trace "0.7.3"]
  	[compojure "1.0.1"]
  	[useful "0.7.6"]
  	[egamble/let-else "1.0.1"]
  	[frinj "0.1.3"]
  	[seesaw "1.4.0"]
  	[quil "1.0.0-SNAPSHOT"]
  	[com.cemerick/friend "0.0.4"]
  	]
  :dev-dependencies [
  	[clj-ns-browser "1.1.0"]
  	[lein-marginalia "0.6.0"]
  	[lein-noir "1.2.1"]
  	[midje "1.3.2-SNAPSHOT"]
  	[trammel "0.7.0"]
  	]
  )
