(defproject kitjensink "1.0.0-SNAPSHOT"
	:description "FIXME: write description"
  :dependencies [
		[org.clojure/clojure "1.3.0"]
  	[org.clojure/tools.namespace "0.1.0"]
  	[org.clojure/tools.logging "0.2.3"]
  	[org.clojure/tools.cli "0.2.1"]
  	[org.clojure/data.csv "0.1.0"]
  	[org.clojure/data.codec "0.1.0"]
  	[org.clojure/core.unify "0.5.2"]
  	[org.clojure/core.memoize "0.5.1"]
  	[org.clojure/core.match "0.2.0-alpha9"]
  	[fs "1.1.2"]
  	[hiccup "0.3.8"]
  	[com.cemerick/pomegranate "0.0.4"]
  	[marginalia "0.7.0-SNAPSHOT"]
  	[lein-noir "1.2.1"]
  	[pinot "0.1.1-SNAPSHOT"]
  	[ns-tracker "0.1.1"]
  	[codox "0.3.4"]
  	[compojure "1.0.1"]
  	[useful "0.7.6"]
  	;[enlive "1.2.0-alpha1"]
  	;[core.logic "0.6.8-SNAPSHOT"]
  	;[algo.generic "0.1.1-SNAPSHOT"]
  	]
  :dev-dependencies [
  	[lein-marginalia "0.6.0"]
  	]
  )
